export BUILT_PRODUCTS_DIR="/Users/caoyuan/Library/Developer/Xcode/DerivedData/ForCoverage-binlaypyjrurfldbnuntosxqkvdv/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/caoyuan/Library/Developer/Xcode/DerivedData/ForCoverage-binlaypyjrurfldbnuntosxqkvdv/Build/Intermediates/ForCoverage.build/Debug-iphonesimulator/ForCoverage.build/Objects-normal"
export OBJROOT="/Users/caoyuan/Library/Developer/Xcode/DerivedData/ForCoverage-binlaypyjrurfldbnuntosxqkvdv/Build/Intermediates"
export SRCROOT="/Users/caoyuan/Project/GitHUB/ForCoverage/ForCoverage"
