export BUILT_PRODUCTS_DIR="/Users/caoyuan/Library/Developer/Xcode/DerivedData/ForCoverage-alcbozyxymagdncytjpcwzjemzej/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="i386"
export OBJECT_FILE_DIR_normal="/Users/caoyuan/Library/Developer/Xcode/DerivedData/ForCoverage-alcbozyxymagdncytjpcwzjemzej/Build/Intermediates/ForCoverage.build/Debug-iphonesimulator/ForCoverage.build/Objects-normal"
export OBJROOT="/Users/caoyuan/Library/Developer/Xcode/DerivedData/ForCoverage-alcbozyxymagdncytjpcwzjemzej/Build/Intermediates"
export SRCROOT="/Users/caoyuan/Desktop/testKIF/ForCoverage"
